<a href="https://colab.research.google.com/github/anshikatyagi23/Machine-Learning/blob/main/Complete_Numpy_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy-Numerial Python

Advantages of Numpy Arrays
Allows several Mathematical Operations
Faster Operations

In [ ]:
import numpy as np

List vs Numpy-Time Taken

In [ ]:
from time import process_time

Time taken  by a list

In [ ]:

pyton_list = [i for i in range(10000)]

start_time = time.process_time() # Use time.process_time() to call the function

pyton_list = [i+5 for i in pyton_list]

end_time = time.process_time() # Use time.process_time() to call the function

print(end_time - start_time)

0.00054715599999966


In [ ]:
np_array = np.array([i for i in range(10000)])

start_time = time.process_time()

np_array += 5

end_time = time.process_time()

print(end_time - start_time)


0.0014028010000002311


Numpy Arrays

In [ ]:
#list
list1=[ 1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array= np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [ ]:
#creating 1D array
a= np.array([1,2,3,4,5])
print(a)


[1 2 3 4 5]


In [ ]:
a.shape

(5,)

In [ ]:
#creating 2 d array
b= np.array([(1,2,3,4),(7,6,5,4)])
print(b)

[[1 2 3 4]
 [7 6 5 4]]


In [ ]:
b.shape

(2, 4)

In [ ]:
c = np.array([(1,2,3,4),(7,6,5,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [7. 6. 5. 8.]]


Initial Placeholders in numpy arrays

In [ ]:
#create a numpy array of zeroes
x= np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#create numpy array of ones
y= np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
z= np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
#identity matrix
a= np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#random values
b= np.random.random((3,4))
print(b)

[[0.55250984 0.25935762 0.36180172 0.90013075]
 [0.73022411 0.62133662 0.33219638 0.16408762]
 [0.84013734 0.7569378  0.93650354 0.20594004]]


In [ ]:
#random value integer
c= np.random.randint(10,100,(3,5))
print(c)

[[97 80 28 41 58]
 [26 51 51 65 42]
 [70 58 38 74 30]]


In [ ]:
#array of evenly spaced
d= np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [ ]:
#array of evenly spaced
e= np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
#convert a list to array
list2=[10,20,30,40,50]

np_array= np.asarray(list2)
print(np_array)

[10 20 30 40 50]


Analysing a numpy array

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[25 11 89 85 12]
 [18 70 45 44 32]
 [43 56 48 20 39]
 [57 53 69 80 50]
 [70 36 37 41 83]]


In [ ]:
print(c.shape)

(5, 5)


In [ ]:
print(c.ndim)

2


In [ ]:
print(c.size)

25


In [ ]:
#checking the datatype values in array
print(c.dtype)

int64


In [ ]:
#Mathematical operations on np array
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]

print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[1 9 8]
 [6 2 8]
 [3 5 5]]
[[15 14 18]
 [15 11 15]
 [11 19 14]]


In [ ]:
print(a+b)

[[16 23 26]
 [21 13 23]
 [14 24 19]]


In [ ]:
print(a-b)

[[-14  -5 -10]
 [ -9  -9  -7]
 [ -8 -14  -9]]


In [ ]:
print(a*b)

[[ 15 126 144]
 [ 90  22 120]
 [ 33  95  70]]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[7 4 1]
 [6 3 5]
 [2 2 2]]
[[15 15 16]
 [12 19 19]
 [18 18 13]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[22 19 17]
 [18 22 24]
 [20 20 15]]
[[ -8 -11 -15]
 [ -6 -16 -14]
 [-16 -16 -11]]
[[105  60  16]
 [ 72  57  95]
 [ 36  36  26]]
[[0.46666667 0.26666667 0.0625    ]
 [0.5        0.15789474 0.26315789]
 [0.11111111 0.11111111 0.15384615]]


Array manipulation

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 5 0]
 [1 2 6]]
(2, 3)


In [ ]:
#transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[4 1]
 [5 2]
 [0 6]]
(3, 2)


In [ ]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[4 1]
 [5 2]
 [0 6]]
(3, 2)


In [ ]:
#reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[5 1 8]
 [2 1 1]]
(2, 3)


In [ ]:
#reshape
b = a.reshape(3,2)
print(b)
print(b.shape)

[[5 1]
 [8 2]
 [1 1]]
(3, 2)
