<a href="https://colab.research.google.com/github/anshikatyagi23/Machine-Learning/blob/main/Part_2_Matrix_Operations_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Matrix Addition

Two Matrices can be added only if they have the same shape

In [2]:
# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])


In [3]:
print(A)

[[2 3]
 [4 5]]


In [4]:

print(B)

[[6 7]
 [8 9]]


In [5]:
A.shape

(2, 2)

In [6]:

B.shape

(2, 2)

Adding two Matrices

In [7]:
sum = A + B

In [8]:
print(sum)

[[ 8 10]
 [12 14]]


In [9]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [10]:
print(matrix_1)

[[7 1 5]
 [8 7 9]
 [9 5 3]]


In [11]:
print(matrix_2)

[[ 0  8 14]
 [13 10  6]
 [14  7 11]]


In [12]:
sum = np.add(matrix_1, matrix_2)

In [13]:
print(sum)

[[ 7  9 19]
 [21 17 15]
 [23 12 14]]


In [16]:
# create two matrices with random values
matrix_3 = np.random.randint(10, size=(3,3))
matrix_4 = np.random.randint(20, size=(3,3))


In [17]:
sum_2 = np.add(matrix_3, matrix_4)

Matrix Subtraction

In [18]:
# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])


In [19]:

print(A)


[[2 3]
 [4 5]]


In [20]:

print(B)

[[6 7]
 [8 9]]


In [21]:

difference = A - B

In [22]:


print(difference)

[[-4 -4]
 [-4 -4]]


In [23]:


# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [24]:
print(matrix_1)

[[1 0 3]
 [7 9 7]
 [0 4 5]]


In [25]:
print(matrix_2)

[[11  6  6]
 [11 14  0]
 [ 0  6  0]]


In [26]:
diff = np.subtract(matrix_1, matrix_2)


In [27]:
print(diff)

[[-10  -6  -3]
 [ -4  -5   7]
 [  0  -2   5]]


Multiplying a matrix by a scalar

In [28]:
x = 5
y = np.random.randint(10, size=(4,4))

print(y)

[[1 2 1 4]
 [4 0 5 7]
 [4 7 8 3]
 [6 2 6 4]]


In [29]:
product = np.multiply(x,y)

In [30]:

print(product)

[[ 5 10  5 20]
 [20  0 25 35]
 [20 35 40 15]
 [30 10 30 20]]


Multiplying 2 Matrices

In [31]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))

In [32]:
print(matrix_3)

[[4 2 2]
 [1 4 1]
 [0 3 4]]


In [33]:
print(matrix_4)

[[2 1 2 1]
 [0 0 3 4]
 [1 4 1 4]]


In [34]:

product = np.dot(matrix_3, matrix_4)

In [35]:

print(product)


[[10 12 16 20]
 [ 3  5 15 21]
 [ 4 16 13 28]]


In [36]:
product.shape

(3, 4)

In [38]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,3))

In [39]:

product = np.dot(matrix_3, matrix_4)

Element wise Matrix Multiplication

In [40]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,3))


In [41]:
print(matrix_3)

[[3 4 4]
 [1 4 0]
 [3 0 3]]


In [42]:
print(matrix_4)

[[0 0 1]
 [2 3 4]
 [3 4 1]]


In [43]:

product = np.multiply(matrix_3, matrix_4)

In [44]:
print(product)

[[ 0  0  4]
 [ 2 12  0]
 [ 9  0  3]]


In [46]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,3))

In [47]:
product = np.multiply(matrix_3, matrix_4)