<a href="https://colab.research.google.com/github/anshikatyagi23/Machine-Learning/blob/main/Part2_Working_with_matrix_in_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Creating a Matrix using numpy

In [2]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)


[[2 3]
 [6 7]]


In [3]:
matrix_1.shape

(2, 2)

In [4]:
matrix_2 = np.array([[10,35,45],[50,64,80],[20,15,90]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [5]:

matrix_2.shape

(3, 3)

Creating Matrices with Random Values

In [6]:
random_matrix = np.random.rand(3,3)
print(random_matrix)


[[0.35131958 0.91217577 0.11861792]
 [0.68198403 0.62115453 0.99210733]
 [0.06879697 0.53244954 0.00132309]]


In [7]:
# creating matrix with random integers
random_integer_matrix = np.random.randint(100, size=(4,5))
print(random_integer_matrix)

[[11 47 95 86 89]
 [75 42 70 20  0]
 [78 32 64 76 64]
 [ 5 63 46 19 89]]


Matrix with all the values as 1

In [8]:
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
matrix_3 = np.ones((2,3), dtype=int)
print(matrix_3)


[[1 1 1]
 [1 1 1]]


In [10]:
matrix_3 = np.ones((10,10), dtype=int)
print(matrix_3)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


Null Matrix or Zero Matrix

In [11]:
null_matrix = np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
null_matrix = np.zeros((7,7))
print(null_matrix)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


Identity Matrix

In [13]:
identity_matrix = np.eye(3,3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
identity_matrix = np.eye(5,5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Transpose of a Matrix

In [15]:
# matrix with random integer values
a = np.random.randint(100, size=(4,5))
print(a)


[[51 82 80  1 94]
 [27 79 23 25 52]
 [53 89 32 60 41]
 [22 94  2 92 33]]


In [16]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)


[[51 27 53 22]
 [82 79 89 94]
 [80 23 32  2]
 [ 1 25 60 92]
 [94 52 41 33]]
